dist: bionic
sudo: require

language: cpp
compiler: gcc

before_install:
    - sudo add-apt-repository -y ppa:team-xbmc/ppa
    - sudo apt-get update && sudo apt-get install -y  libegl1-mesa-dev 
                                                      libgles2-mesa-dev 
                                                      libsdl2-dev 
                                                      libsdl2-image-dev 
                                                      nlohmann-json-dev 
    
before_script:
    - mkdir build
    - cd build
    - cmake ..

script:
    - make  

branches:
    only:
        - master
        - development


notifications:
    email:
        recipients:
            - fedee962@outlook.com
            - elianagam2@gmail.com
            - leobellaera@gmail.com

        on_success: never
        on_failure: always


